# Generated by Django 2.1.2 on 2018-10-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='customers',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='customers',
            name='country',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customers',
            name='state',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='zipcode',
            field=models.CharField(max_length=33),
        ),
        migrations.AlterField(
            model_name='movies',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
